[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.mbstring", "php83Extensions.openssl", "php83Extensions.session", "php83Extensions.fileinfo"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
